# This YAML file defines concepts, co-indicators, and features
# for health outcomes analysis in All of Us (AOU) data.
# It serves as a configuration template for data extraction and ML model inputs.

metadata:
  schema_version: 1.0.0
  description: "Definition of COPD, related co-indicators, and relevant features for analysis."
  created_date: "2025-05-30" # Consider automating this or updating manually

# Primary target condition or outcome for this specific analysis configuration
outcome:
  name: copd
  domain: condition_occurrence
  description: Diagnosis of chronic obstructive pulmonary disease (COPD)
  concepts_include:
    # Original broad COPD concepts
    - 255573      # SNOMED code for COPD (general)
    - 321316      # SNOMED code for chronic bronchitis
    - 312327      # SNOMED code for emphysema (original)
    # More granular SNOMED child concepts for COPD and related conditions
    - 46274062    # SNOMED code for Asthma-chronic obstructive pulmonary disease overlap syndrome 
    - 44791725    # SNOMED code for Very severe chronic obstructive pulmonary disease 
    - 313299006   # SNOMED code for Severe chronic obstructive pulmonary disease
    - 313297008   # SNOMED code for Moderate chronic obstructive pulmonary disease
    - 313296004   # SNOMED code for Mild chronic obstructive pulmonary disease
    - 135836000   # SNOMED code for End stage chronic obstructive airways disease
    - 47938003    # SNOMED code for Chronic obliterative bronchiolitis
    - 7433001     # SNOMED code for Pulmonary emphysema (additional specific code)
    - 196001008   # SNOMED code for Chronic obstructive pulmonary disease with acute lower respiratory infection
    - 195951007   # SNOMED code for Acute exacerbation of chronic obstructive airways disease
  concepts_exclude: [4288734] # SNOMED code for Bronchiolar disease

# Co-morbidities or related conditions that serve as indicators alongside the target condition
co_indicators:
  - name: obesity
    domain: condition_occurrence
    description: Diagnosis of obesity
    concepts_include:
      - 4149162    # SNOMED code for obesity
    concepts_exclude: []

  - name: diabetes
    domain: condition_occurrence
    description: Diagnosis of type 2 diabetes mellitus
    concepts_include:
      - 201826     # SNOMED code for type 2 diabetes mellitus
    concepts_exclude: []

  - name: cardiovascular_disease
    domain: condition_occurrence
    description: History of cardiovascular diseases (e.g., heart failure, MI)
    concepts_include:
      - 319835     # SNOMED code for heart failure
      - 312327     # SNOMED code for myocardial infarction
    concepts_exclude: []

# Individual variables or characteristics to be extracted for modeling
features:
  - name: smoking_status_obs # Keep this one as is
    domain: observation
    type: categorical
    description: Smoking status from observation domain
    concepts_include:
      - 1585856
      - 40652439
    concepts_exclude: []

  - name: smoking_status_measurement # <--- RENAMED THIS ONE!
    domain: measurement
    type: categorical
    description: Smoking status from measurement domain
    concepts_include:
      - 40652439
    concepts_exclude: []

  - name: smoking_status_survey # Keep this one as is
    domain: ds_survey
    type: categorical
    description: Smoking status from survey answers
    concepts_include:
      - 45880274
    concepts_exclude: []

  - name: alcohol_use_survey
    domain: ds_survey
    type: binary
    description: History of alcohol use from survey answers
    concepts_include:
      - 36310580    # Alcohol answer from survey
    concepts_exclude: []

  - name: alcohol_use_cond
    domain: condition_occurrence
    type: binary
    description: Alcohol-related condition from condition domain
    concepts_include:
      - 433753      # Alcohol related condition
    concepts_exclude: []

  - name: year_of_birth
    domain: person
    type: continuous
    description: Year of birth from the person table
    # For direct fields from a table (like year_of_birth from 'person'),
    # concept IDs might not apply directly, or they might define how to derive the feature.
    concepts_include: []
    concepts_exclude: []

  - name: bmi
    domain: measurement
    type: continuous
    description: Body Mass Index (BMI)
    concepts_include:
      - 3038553    # OMOP concept ID for BMI
    concepts_exclude: []

  # - name: education_level
  #   domain: observation
  #   type: categorical
  #   description: Highest education level attained
  #   concepts_include:
  #     - 1585249    # OMOP code for education level
  #   concepts_exclude: []

  # - name: housing_insecurity
  #   domain: observation
  #   type: binary
  #   description: Reported housing insecurity or instability
  #   concepts_include:
  #     - 765063     # OMOP concept ID for housing insecurity
  #   concepts_exclude: []
