outcome:
  name: copd
  domain: condition_occurrence
  description: Diagnosis of chronic obstructive pulmonary disease (COPD)
  concepts_include:
    - 255573      # SNOMED code for COPD
    - 321316      # SNOMED code for chronic bronchitis
    - 312327      # SNOMED code for emphysema
    - 257004      # SNOMED code for Acute exacerbation of chronic obstructive airways disease
    # More granular SNOMED child concepts for COPD and related conditions
    - 46274062    # Asthma-chronic obstructive pulmonary disease overlap syndrome (Note: This is a very long concept ID, potentially an AOU-specific or complex SNOMED expression ID)
    - 44791725    # Very severe chronic obstructive pulmonary disease (Note: This is a very long concept ID, potentially an AOU-specific or complex SNOMED expression ID)
    - 313299006   # SNOMED code for Severe chronic obstructive pulmonary disease
    - 313297008   # SNOMED code for Moderate chronic obstructive pulmonary disease
    - 313296004   # SNOMED code for Mild chronic obstructive pulmonary disease
    - 135836000   # SNOMED code for End stage chronic obstructive airways disease
    - 47938003    # SNOMED code for Chronic obliterative bronchiolitis
    - 7433001     # SNOMED code for Pulmonary emphysema (additional specific code)
    - 196001008   # SNOMED code for Chronic obstructive pulmonary disease with acute lower respiratory infection
    - 195951007   # SNOMED code for Acute exacerbation of chronic obstructive airways disease
  concepts_exclude: [4288734] # SNOMED code for Bronchiolar disease


co_indicators:
  - name: obesity
    domain: condition_occurrence
    description: Diagnosis of obesity
    concepts_include:
      - 4149162    # SNOMED code for obesity
    concepts_exclude: []

  - name: diabetes
    domain: condition_occurrence
    description: Diagnosis of type 2 diabetes mellitus
    concepts_include:
      - 201826     # SNOMED code for type 2 diabetes mellitus
    concepts_exclude: []

  - name: cardiovascular_disease
    domain: condition_occurrence
    description: History of cardiovascular diseases (e.g., heart failure, MI)
    concepts_include:
      - 319835     # SNOMED code for heart failure
      - 312327     # SNOMED code for myocardial infarction
    concepts_exclude: []

features:
  - name: smoking_status
    domain: observation
    type: categorical
    description: Smoking status (never, former, current)
    concepts_include:
      - 4305494    # current smoker
      - 4305495    # former smoker
      - 4305496    # never smoked
    concepts_exclude: []
    required: true
    default: null

  - name: alcohol_use
    domain: observation
    type: binary
    description: History of alcohol use
    concepts_include:
      - 4319335    # Alcohol user
    concepts_exclude: []
    required: true
    default: null

  - name: year_of_birth
    domain: person
    type: continuous
    description: Year of birth from the person table
    concepts_include: []    # Not applicable, but keeps structure consistent
    concepts_exclude: []
    required: true
    default: null

  - name: bmi
    domain: measurement
    type: continuous
    description: Body Mass Index (BMI)
    concepts_include:
      - 3038553    # OMOP concept ID for BMI
    required: true
    default: null


  # - name: education_level
  #   domain: observation
  #   type: categorical
  #   description: Highest education level attained
  #   concepts_include:
  #     - 1585249    # OMOP code for education level
  #   required: true
  #   default: null

  # - name: housing_insecurity
  #   domain: observation
  #   type: binary
  #   description: Reported housing insecurity or instability
  #   concepts_include:
  #     - 765063     # OMOP concept ID for housing insecurity
  #   required: true
  #   default: null
